### ISSUE TITLE
Implement insurance connector

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/anchor-collateral-steth#14]
The current implementation has no code (it returns zero always) for the insurance connector (see `InsuranceConnector.vy`).
It could be implemented by injecting dependency on the `SelfOwnStETHBurner` contract, which was developed to carry out the [LIP-6](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-6.md).

**Comment by skozin** [comment]
Closed in #13.
